[package]
name = "office-controller"
version = "0.1.0"
authors = ["Keith <hnefatl@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"


[[bin]]
name = "office-controller"
harness = false            # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []

experimental = ["esp-idf-svc/experimental"]

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.49", features = [
    "embassy-time-driver",
    "embassy-sync",
] }
embassy-executor = { version = "0.6", features = [
    "arch-std",
    "executor-thread",
    "integrated-timers",
    "log",
] }
embassy-sync = "0.6"
embassy-time = "0.3"
anyhow = "1.0"
embedded-svc = "0.28"
serde = "1.0"
embedded-io-adapters = { version = "0.6", features = ["std"] }
serde_json = "1.0"
zeroize = { version = "1.8.1", features = ["derive"] }
config = { path = "config" }

[build-dependencies]
embuild = "0.32.0"
cc = "=1.1.30"               # Necessary until a new version of `esp-idf-sys` is released
config = { path = "config" }
