[build]
#target = "riscv32imc-unknown-none-elf"
target = "xtensa-esp32-none-elf"

[target.riscv32imc-unknown-none-elf]
runner = "./flash_all.sh"
rustflags = ["-C", "link-arg=-Tlinkall.x"]


[unstable]
build-std = ["core", "alloc"]

[env]
MCU="esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.2"

# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174 
CRATE_CC_NO_DEFAULTS = "1"
