[build]
target = "xtensa-esp32-none-elf"
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.xtensa-esp32-none-elf]
runner = "./flash_all.sh"

[unstable]
build-std = ["core", "alloc"]

[env]
ESP_WIFI_COUNTRY_CODE = "GB"
ESP_WIFI_PHY_ENABLE_USB = "false"
