[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-svc = { version = "0.28", features = ["use_serde"] }
serde = "1.0"
toml = "0.8"

[build-dependencies]
embuild = "0.32.0"
