[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
embedded-svc = { version = "0.28", features = ["use_serde"] }
serde = "1.0"
toml = "0.8"
nonempty = { version = "0.10", features = ["serialize"] }

[build-dependencies]
embuild = "0.32.0"
